---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
grubInstall: "/usr/local/sbin/persisos-grub-install"
grubMkconfig: "update-grub"
grubCfg: "/boot/grub/grub.cfg"
# Debian's EFI GRUB binaries expect their configuration under EFI/debian.
efiBootloaderId: "debian"
efiBootMgr: "efibootmgr"
installEFIFallback: false
installEpilog: ""
