---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
createHybridBootloaderLayout: true

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"
