---
dontChroot: false
script:
  - "/usr/bin/apt-get -y autoremove --purge"
  - "/usr/bin/rm -f /usr/share/applications/install-persisos.desktop"
  - "/usr/bin/rm -f /usr/share/applications/calamares.desktop"
  - "/usr/bin/rm -rf /etc/calamares"
  - "/usr/bin/rm -f /usr/local/sbin/persisos-grub-install"
  - "/usr/bin/rm -f /etc/sddm.conf.d/zz-persisos-live-autologin.conf"
  - "/usr/bin/rm -f '/etc/skel/Desktop/Install PersisOS.desktop'"
  - "/usr/bin/find /home -type f -name 'Install PersisOS.desktop' -delete"
  - "/usr/bin/bash -c 'if [ \"${USER}\" != user ] && /usr/bin/id user >/dev/null 2>&1; then /usr/sbin/userdel --remove user; fi'"
