---
dontChroot: false
script:
  - "/usr/bin/apt-get -y autoremove --purge"
  - "/usr/bin/rm -f /usr/share/applications/install-yaran.desktop"
  - "/usr/bin/rm -f /usr/share/applications/calamares.desktop"
  - "/usr/bin/rm -rf /etc/calamares"
  - "/usr/bin/rm -f /usr/local/sbin/yaran-grub-install"
  - "/usr/bin/rm -f /etc/sddm.conf.d/zz-yaran-live-autologin.conf"
  - "/usr/bin/rm -f '/etc/skel/Desktop/Install Yaran Linux.desktop'"
  - "/usr/bin/find /home -type f -name 'Install Yaran Linux.desktop' -delete"
  - "/usr/bin/bash -c 'if [ \"${USER}\" != user ] && /usr/bin/id user >/dev/null 2>&1; then /usr/sbin/userdel --remove user; fi'"
