---
defaultGroups:
    - name: sudo
      must_exist: false
      system: false
    - name: audio
    - name: video
    - name: plugdev
    - name: netdev
    - name: input

autologinGroup: autologin
doAutologin: true
sudoersGroup: sudo
setRootPassword: true
doReusePassword: false
defaultShell: /bin/bash
