---
modules-search: [ local ]

instances:
  - id: cleanup_installer
    module: shellprocess
    config: shellprocess-cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - displaymanager
      - hwclock
      - initramfs
      - grubcfg
      - bootloader
      - packages
      - shellprocess@cleanup_installer
      - umount
  - show:
      - finished

branding: PersisOS
prompt-install: true
dont-chroot: false
oem-setup: false
